language: java
sudo: false
jdk:
- openjdk7

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
# ensure we have ruby
- travis_wait 45 ruby --version
- travis_wait 45 gem install bundler
- travis_wait 45 bundle install
# fetch 3rd party apis and such
- travis_wait 45 git submodule update --init
- travis_wait 45 chmod +x ./gradlew

install: travis_wait 45 ./gradlew setupCIWorkspace -S

script:
- travis_wait 45 ./gradlew build
- travis_wait 45 bundle exec ./tools/split_jars.rb
- travis_wait 45 ls -la build/libs
- travis_wait 45 ls -la build/packages
- travis_wait 45 bundle exec ./tools/checksum_builds.rb | tee ./checksums.txt
- travis_wait 45 bundle exec ./tools/attribution_cross_check.rb

# Deploy the artifacts back to GitHub
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
  - "checksums.txt"
  - "build/libs/growthcraft-*-complete.jar"
  - "build/libs/growthcraft-*-api.jar"
  - "build/libs/growthcraft-*-deobf.jar"
  - "build/libs/growthcraft-*-javadoc.jar"
  - "build/libs/growthcraft-*-sources.jar"
  # separate jars
  - "build/packages/growthcraft-*-complete-*.jar"
  - "build/packages/growthcraft-*-deobf-*.jar"
  skip_cleanup: true
  on:
    tags: true
